server {
    listen 80;
    server_name pymeweb.app www.pymeweb.app;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # CAMBIA ESTO POR LA IP PRIVADA DE TU EC2 BACKEND (ej: 10.0.x.x)
        proxy_pass http://10.0.136.107:8080; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}