server {
    listen 80;
    server_name pymeweb.app www.pymeweb.app;

    
    location / {
        return 301 https://$host$request_uri;
    }

    
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl;
    server_name pymeweb.app www.pymeweb.app;

    
    ssl_certificate /etc/letsencrypt/live/pymeweb.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pymeweb.app/privkey.pem;

    
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

   
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    
    location /api/ {
        proxy_pass http://10.0.136.107:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}